<Project>
  <Import Project="$(MSBuildThisFileDirectory)eng/Broiler.Packaging.props" />
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release</Configurations>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <UnicodeEmojiVersion>16.0</UnicodeEmojiVersion>
    <PackageProjectUrl>https://github.com/Broiler-Platform/Broiler.Unicode</PackageProjectUrl>
    <PackageTags>broiler;unicode;cldr;emoji</PackageTags>
  </PropertyGroup>
</Project>
